import "./globals.css";

import { cn } from "@nextui-org/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { Toaster } from "sonner";

import { authOptions } from "./api/auth/[...nextauth]/auth.config";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Whisper",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn("min-h-screen antialiased", inter.className)}>
				<Toaster richColors position="top-center" />
				<Providers session={session}>{children}</Providers>
			</body>
		</html>
	);
}
